all:
	#ocamlfind opt -rectypes -package visitors.runtime,visitors.ppx -linkpkg test001.ml
	#ocamlfind opt -rectypes -package visitors.runtime,visitors.ppx -linkpkg -dsource test003.ml
	#ocamlfind opt -rectypes -package visitors.runtime,visitors.ppx -linkpkg -dsource test003.ml
	#ocamlfind opt -rectypes -package visitors.runtime,visitors.ppx -linkpkg -dsource test004.ml
	ocamlfind opt -rectypes -package visitors.runtime,visitors.ppx -linkpkg -dsource test005.ml

