lib: [
  "_build/install/default/lib/pa_gt/META" {"META"}
  "_build/install/default/lib/pa_gt/opam" {"opam"}
  "_build/install/default/lib/pa_gt/pa_gt__Camlp5Helpers.cmi" {"pa_gt__Camlp5Helpers.cmi"}
  "_build/install/default/lib/pa_gt/pa_gt__Camlp5Helpers.cmx" {"pa_gt__Camlp5Helpers.cmx"}
  "_build/install/default/lib/pa_gt/pa_gt__Camlp5Helpers.cmt" {"pa_gt__Camlp5Helpers.cmt"}
  "_build/install/default/lib/pa_gt/Camlp5Helpers.ml" {"Camlp5Helpers.ml"}
  "_build/install/default/lib/pa_gt/pa_gt__Core2.cmi" {"pa_gt__Core2.cmi"}
  "_build/install/default/lib/pa_gt/pa_gt__Core2.cmx" {"pa_gt__Core2.cmx"}
  "_build/install/default/lib/pa_gt/pa_gt__Core2.cmt" {"pa_gt__Core2.cmt"}
  "_build/install/default/lib/pa_gt/core2.ml" {"core2.ml"}
  "_build/install/default/lib/pa_gt/pa_gt__Extension.cmi" {"pa_gt__Extension.cmi"}
  "_build/install/default/lib/pa_gt/pa_gt__Extension.cmx" {"pa_gt__Extension.cmx"}
  "_build/install/default/lib/pa_gt/pa_gt__Extension.cmt" {"pa_gt__Extension.cmt"}
  "_build/install/default/lib/pa_gt/extension.ml" {"extension.ml"}
  "_build/install/default/lib/pa_gt/pa_gt.cmi" {"pa_gt.cmi"}
  "_build/install/default/lib/pa_gt/pa_gt.cmx" {"pa_gt.cmx"}
  "_build/install/default/lib/pa_gt/pa_gt.cmt" {"pa_gt.cmt"}
  "_build/install/default/lib/pa_gt/pa_gt.ml-gen" {"pa_gt.ml-gen"}
  "_build/install/default/lib/pa_gt/pa_gt.cma" {"pa_gt.cma"}
  "_build/install/default/lib/pa_gt/pa_gt.cmxa" {"pa_gt.cmxa"}
  "_build/install/default/lib/pa_gt/pa_gt.a" {"pa_gt.a"}
  "_build/install/default/lib/pa_gt/pa_gt.cmxs" {"pa_gt.cmxs"}
  "_build/install/default/lib/pa_gt/pa_gt.dune" {"pa_gt.dune"}
]
doc: [
  "_build/install/default/doc/pa_gt/README.md"
]
