(env
 (_
  (flags
   (:standard -w -27-32+9 -warn-error -A))))

(library
 (name GTCommon)
 (public_name GT.common)
 (libraries ppxlib ppxlib.stdppx ocamlgraph)
 (modules HelpersBase Naming Expander GTHELPERS_sig Plugin_intf Plugin)
 (synopsis
  "Actual code that perform codegeneration. Will used for creating new plugins")
 (flags
  (:standard -w -32-9 -warn-error -A))
 (instrumentation
  (backend bisect_ppx))
 (preprocess
  (pps ppxlib.metaquot))
 (foreign_stubs
  (language c)
  (names common_stubs)))

(library
 (name GTCommon_tests)
 (modules GTCommon_tests)
 (inline_tests)
 (libraries GTCommon)
 (preprocess
  (pps ppxlib.metaquot ppx_inline_test_nobase)))
