name: Build master in docker (OCaml 5.2)

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'

env:
  OPAMROOT: /home/opam/.opam
  OPAMCONFIRMLEVEL: unsafe-yes
  GT_WITH_DOCS: yes

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    runs-on: ${{ matrix.os }}
    container:
      image: ocaml/opam:ubuntu-lts-ocaml-5.2
      options: --user root # Kind of important dirty hack
      #options: --user opam               # dirty hack

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - run: |
          sudo apt-get update
          sudo apt-get install pkg-config libpcre2-dev m4 -y
      - run: opam --version

      - name: bisect many not work without it
        if: false #we will not run coverage in 5.2
        run: |
          git config --global --add safe.directory /__w/GT/GT
          #git submodule update --init


      - name: Install dependecies for documentation
        run: |
          sudo apt-get install pkg-config libpcre2-dev -y

      - run: opam install . --deps-only --with-test --with-doc
      - run: opam exec -- dune build @check --profile=release
      - run: opam exec -- dune test --profile=release

      - name: Installing using Opam
        run: |
          opam exec -- dune build @install
          opam exec -- dune install

      - name: List files
        run: opam show --list-files GT
