name: Build master in docker (OCaml 5.3 and 5.5)

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - 'master'
env:
  OPAMCONFIRMLEVEL: unsafe-yes
  GT_WITH_DOCS: yes
  OPAMROOT: /home/opam/.opam

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        containers: [ 'zanuda53', 'zanuda55' ]

    runs-on: ubuntu-latest
    container:
      image: kakadu18/ocaml:${{ matrix.containers }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.containers }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - run: |
          sudo apt-get update
          sudo apt-get install pkg-config libpcre2-dev m4 -y

      #- run: mv `which opam-dev` `which opam`
      - run: opam --version

      - run: opam install . --deps-only --with-test --with-doc
      - run: opam exec -- dune build @check --profile=release
      - run: opam exec -- dune test --profile=release

      - name: Installing using Opam
        run: |
          opam exec -- dune build @install
          opam exec -- dune install

      - name: List files
        run: opam show --list-files GT
