name: Build PR

on:
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - 'master'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        containers: [ 'zanuda414' ]

    runs-on: ubuntu-latest
    container:
      image: kakadu18/ocaml:${{ matrix.containers }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.containers }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - run: opam --version

      - run: opam install . --deps-only --with-test --with-doc
      - run: opam exec -- dune build @check --profile=release
      - run: opam exec -- dune test --profile=release

      - name: Installing using Opam
        run: |
          opam exec -- dune build @install
          opam exec -- dune install

      - name: List files
        run: opam show --list-files GT

      # TODO: coverage
